### PR TITLE
Add workaround for object_pairs_hook=OrderedDict in Python 2.6 on RHEL6 hosts

### PR DESCRIPTION
**Pull request by nicholas-brown**

### CODE REVIEW

**Comment by nicholas-brown** [comment]
Before this change I get the following on a RHE6u7 host.

  File "test.py", line 21, in <module>
    print sf.query(<removed>)
  File "./simple_salesforce/api.py", line 286, in query
    return result.json(object_pairs_hook=OrderedDict)
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib64/python2.6/site-packages/simplejson/__init__.py", line 318, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'

Relevant packages:
python-2.6.6-64.el6.x86_64
python-requests-2.6.0-3.el6.noarch
python-simplejson-2.0.9-3.1.el6.x86_64

**Comment by nickcatal** [comment]
`object_pairs_hook=OrderedDict` should work in python 2.6 as long as you're using simplejson 2.1.0 or higher.

So try updating the simplejson library.

**Comment by nicholas-brown** [comment]
Thanks @nickcatal.  Upgrading simplejson isn't really realistic for me (I'm trying to stick with packages in the mainline RHEL6 repository), but I'll close this PR. I do appreciate the info though, I'll update my fork to test the simplejson version instead of Python version.
